development:
  adapter: postgresql
  database: ice_pick_development
  username: [<%='augustinevontrapp'%>]
  password: [<%='Chamois111'%>]
  host: localhost

test:
  adapter: postgresql
  database: ice_pick_test
